
version: 2

models:

  - name: stg_warehouses
    description: "all FCs we track"
    columns:
      - name: region_id
        description: "Region ID (int.)"
      - name: physical_country
        description: "Country abbreviation"
      - name: warehouse_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: site_type
        description: "the type of FC (ARS, TSSL)"

  - name: stg_bins_dump
    description: "bin level data by day"
    columns:
      - name: snapshot_day
      - name: region_id
      - name: warehouse_id
      - name: pick_area_name
      - name: bin_id
      - name: is_locked
      - name: bin_usage_name      
      - name: bin_type_name
      - name: bin_bay
      - name: bin_module
      - name: bin_height
      - name: rack
      - name: shelf
      - name: mrg_key
        description: "primary key"


  - name: stg_capacity_utilization
    description: "capacity utilization of bins + bay level data"
    columns:
      - name: snapshot_day
      - name: region_id
      - name: warehouse_id
      - name: container_id
      - name: bin_id
      - name: bin_type
      - name: bin_usage
      - name: drop_zone
      - name: pick_area
      - name: unique_asin_count
      - name: max_unique_asin_count
      - name: total_units
      - name: total_inventory_volume
      - name: gross_bin_volume
      - name: target_utilization
      - name: capacity
      - name: shelf
      - name: bay_id
      - name: bay_type
      - name: aisle_number
      - name: aisle
      - name: floor
      - name: pick_mod
      - name: mrg_key
        description: "primary key"

  - name: stg_bays_dump
    description: "bay level data for each bin ID"
    columns:
      - name: region_id    
      - name: snapshot_day
      - name: warehouse_id
      - name: bin_id
      - name: bay_type
      - name: mrg_key
        description: "primary key"
    
  - name: stg_vet_tenure
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: region_id        
      - name: warehouse_id
      - name: balance_date
      - name: employee_id
      - name: employee_login
      - name: process_path
      - name: cumulative_hrs_worked
      - name: tenure
      - name: mrg_key


  - name: stg_bee_pick
    description: "bin edit entries pick raw data with lag functions"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: person
      - name: old_bin_id
      - name: container
      - name: quantity
      - name: snapshot_day      
      - name: entry_date
      - name: distributor_order_id
      - name: mrg_key
      - name: previous_pick_time_utc
      - name: previous_warehouse_id
      - name: previous_container
      - name: previous_bin
      - name: previous_user_id


  - name: stg_bee_stow
    description: "bin edit entries stow raw data with lag functions"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: person
      - name: container
      - name: new_bin_id
      - name: quantity
      - name: snapshot_day
      - name: entry_date
      - name: distributor_order_id
      - name: mrg_key
      - name: previous_stow_time_utc
      - name: previous_warehouse_id
      - name: previous_container
      - name: previous_bin
      - name: previous_user_id




  - name: core_bin_tbl
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: snapshot_day
      - name: region_id
      - name: warehouse_id
      - name: pick_area_name
      - name: bay_type
      - name: bin_id
      - name: bin_type_name
      - name: bin_usage_name
      - name: is_locked
      - name: cumulative_height
      - name: total_height
      - name: bin_height_category
      - name: mrg_key


  - name: core_fullness
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: region_id    
      - name: balance_date
      - name: warehouse_id
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: mod
      - name: is_locked
      - name: fullness
      - name: target_utilization
      - name: cube
      - name: capacity   
      - name: gross_bin_volume
      - name: units


  - name: core_vet_tenure
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: region_id    
      - name: warehouse_id
      - name: balance_date
      - name: process_path
      - name: vet_emps
      - name: total_emps
      - name: vet_pct


  - name: core_pick_tbb_bee
    description: "pick TBB from bin edit entries"
    columns:
      - name: region_id    
      - name: balance_date
      - name: warehouse_id
      - name: container_type
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: secs
      - name: volume

  - name: core_stow_tbb_bee
    description: "stow TBB from bin edit entries"
    columns:
      - name: region_id    
      - name: balance_date
      - name: warehouse_id
      - name: container_type
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: secs
      - name: volume


  - name: core_pick_tbb_aft
    description: "pick TBB from aft pins pick action bi"
    columns:
      - name: region_id
      - name: balance_date
      - name: warehouse_id
      - name: container_type
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: secs
      - name: volume
