
version: 2

models:

  - name: bins_dump
    description: "bin level data by day"
    columns:
      - name: snapshot_day
      - name: region_id
      - name: warehouse_id
      - name: pick_area_name
      - name: bin_id
      - name: bin_type_name
      - name: bin_bay
      - name: bin_module
      - name: bin_height
      - name: rack
      - name: shelf
      - name: mrg_key
        description: "primary key"
