
version: 2

models:


#---------- staging tables -----------#

  - name: stg_warehouses
    description: "all FCs we track"
    columns:
      - name: region_id
        description: "Region ID (int.)"
      - name: physical_country
        description: "Country abbreviation"
      - name: warehouse_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: site_type
        description: "the type of FC (ARS, TSSL)"

  - name: stg_bins_dump
    description: "bin level data by day"
    columns:
      - name: snapshot_day
      - name: region_id
      - name: warehouse_id
      - name: pick_area_name
      - name: bin_id
      - name: is_locked
      - name: bin_usage_name      
      - name: bin_type_name
      - name: bin_bay
      - name: bin_module
      - name: bin_height
      - name: rack
      - name: shelf
      - name: mrg_key
        description: "primary key"


  - name: stg_capacity_utilization
    description: "capacity utilization of bins + bay level data"
    columns:
      - name: snapshot_day
      - name: region_id
      - name: warehouse_id
      - name: container_id
      - name: bin_id
      - name: bin_type
      - name: bin_usage
      - name: drop_zone
      - name: pick_area
      - name: unique_asin_count
      - name: max_unique_asin_count
      - name: total_units
      - name: total_inventory_volume
      - name: gross_bin_volume
      - name: target_utilization
      - name: capacity
      - name: shelf
      - name: bay_id
      - name: bay_type
      - name: aisle_number
      - name: aisle
      - name: floor
      - name: pick_mod
      - name: mrg_key
        description: "primary key"

  - name: stg_bays_dump
    description: "bay level data for each bin ID"
    columns:
      - name: region_id    
      - name: snapshot_day
      - name: warehouse_id
      - name: bin_id
      - name: bay_type
      - name: mrg_key
        description: "primary key"
    
  - name: stg_vet_tenure
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: region_id        
      - name: warehouse_id
      - name: balance_date
      - name: employee_id
      - name: employee_login
      - name: process_path
      - name: cumulative_hrs_worked
      - name: tenure
      - name: mrg_key


  - name: stg_bee_pick
    description: "bin edit entries pick raw data with lag functions"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: person
      - name: old_bin_id
      - name: container
      - name: quantity
      - name: snapshot_day      
      - name: entry_date
      - name: distributor_order_id
      - name: mrg_key
      - name: previous_pick_time_utc
      - name: previous_warehouse_id
      - name: previous_container
      - name: previous_bin
      - name: previous_user_id


  - name: stg_bee_stow
    description: "bin edit entries stow raw data with lag functions"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: person
      - name: container
      - name: new_bin_id
      - name: quantity
      - name: snapshot_day
      - name: entry_date
      - name: distributor_order_id
      - name: mrg_key
      - name: previous_stow_time_utc
      - name: previous_warehouse_id
      - name: previous_container
      - name: previous_bin
      - name: previous_user_id


  - name: stg_uit
    description: "BMI data from wwaces_ddl.daily_warehouse_fact, pulling idle time hrs"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: balance_date
      - name: process_path
      - name: total_productive_hours
      - name: total_direct_hours
      - name: unknown_idle_time_hours
      - name: total_units
      - name: productive_time_percentage


  - name: stg_faststart_strongfinish
    description: "BMI data from wwaces_ddl.daily_warehouse_fact, pulling fast start and strong finish hrs"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: balance_date
      - name: process_path
      - name: faststart_lost_hrs
      - name: strongfinish_lost_hrs

  - name: stg_fcfinance_dat_ppr_data_v4
    description: "fcfinance PPR actual volume and hours for all eight process paths we track in Olympus"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: balance_date
      - name: process_id
      - name: act_vol
      - name: act_hrs

#---------- core tables -----------#

  - name: core_bin_tbl
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: snapshot_day
      - name: region_id
      - name: warehouse_id
      - name: pick_area_name
      - name: bay_type
      - name: bin_id
      - name: bin_type_name
      - name: bin_usage_name
      - name: is_locked
      - name: cumulative_height
      - name: total_height
      - name: bin_height_category
      - name: mrg_key


  - name: core_fullness
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: region_id    
      - name: balance_date
      - name: warehouse_id
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: mod
      - name: is_locked
      - name: fullness
      - name: target_utilization
      - name: cube
      - name: capacity   
      - name: gross_bin_volume
      - name: units


  - name: core_vet_tenure
    description: "combines bin ID level and capacity (+baytype) data"
    columns:
      - name: region_id    
      - name: warehouse_id
      - name: balance_date
      - name: process_path
      - name: vet_emps
      - name: total_emps
      - name: vet_pct


  - name: core_pick_tbb_bee
    description: "pick TBB from bin edit entries"
    columns:
      - name: region_id    
      - name: balance_date
      - name: warehouse_id
      - name: container_type
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: secs
      - name: volume

  - name: core_stow_tbb_bee
    description: "stow TBB from bin edit entries"
    columns:
      - name: region_id    
      - name: balance_date
      - name: warehouse_id
      - name: container_type
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: secs
      - name: volume


  - name: core_pick_tbb_aft
    description: "pick TBB from aft pins pick action bi"
    columns:
      - name: region_id
      - name: balance_date
      - name: warehouse_id
      - name: container_type
      - name: bay_type
      - name: bin_type
      - name: bin_height_category
      - name: secs
      - name: volume


  - name: core_fcfinance_ppr_v4
    description: "rollup of the raw PPR actuals per process path"
    columns:
      - name: region_id
      - name: balance_date
      - name: warehouse_id
      - name: process_path
      - name: act_vol
      - name: act_hrs
      - name: act_uph


#---------- master tables -----------#


  - name: master_stow_non_ar
    description: "non-AR stow metrics aggregated"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: balance_date
      - name: bay_type
      - name: bin_type
      - name: container_type
      - name: act_vol
      - name: act_hrs
      - name: act_uph
      - name: cube
      - name: capacity
      - name: fullness_pct
      - name: fullness_type
      - name: vet_emps
      - name: total_emps
      - name: vet_pct
      - name: uit_hrs
      - name: total_direct_hrs
      - name: uit_pct
      - name: faststart_lost_hrs
      - name: strongfinish_lost_hrs


#---------- master cbrs tables -----------#

  - name: master_cbrs_stow_non_ar
    description: "non-AR stow metrics aggregated"
    columns:
      - name: region_id
      - name: warehouse_id
      - name: ranking_group
      - name: balance_date
      - name: bay_type
      - name: bin_type
      - name: container_type
      - name: fullness_type
      - name: act_vol
      - name: act_hrs
      - name: act_uph
      - name: cube
      - name: capacity
      - name: fullness_pct
      - name: vet_emps
      - name: total_emps
      - name: vet_pct
      - name: vet_target
      - name: uit_hrs
      - name: total_direct_hrs
      - name: uit_pct
      - name: faststart_lost_hrs
      - name: strongfinish_lost_hrs
      - name: stt_upt_target
      - name: stt_uit_target
      - name: stt_acu_target
      - name: stt_cct_target
      - name: stt_apc_target
      - name: stt_bpa_target
      - name: stt_tlst_target
      - name: stt_bincol_target
      - name: stt_mix_target
      - name: cbrs_hours
      - name: cbrs_hours_act_stt
      - name: cbrs_hours_stt_upt
      - name: cbrs_hours_stt_acu
      - name: cbrs_hours_stt_uit
      - name: cbrs_hours_stt_cct
      - name: cbrs_hours_stt_apc
      - name: cbrs_hours_stt_bpa
      - name: cbrs_hours_stt_tlst
      - name: cbrs_hours_stt_bincol
      - name: cbrs_hours_stt_mix



      
#---------- reporting tables -----------#

  - name: final_stow_non_ar
    description: "non-AR stow metrics aggregated"
    columns:
      - name: intervl
      - name: region_id
      - name: warehouse_id
      - name: ranking_group
      - name: balance_date
      - name: bay_type
      - name: bin_type
      - name: container_type
      - name: fullness_type
      - name: act_volume
      - name: act_hours
      - name: act_uph
      - name: total_cube
      - name: total_capacity
      - name: fullness_pct
      - name: vet_employees
      - name: total_employees
      - name: vet_pct
      - name: vet_target
      - name: uit_hours
      - name: total_direct_hours
      - name: uit_pct
      - name: faststart_lost_hours
      - name: strongfinish_lost_hours
      - name: stt_upt_target
      - name: stt_uit_target
      - name: stt_acu_target
      - name: stt_cct_target
      - name: stt_apc_target
      - name: stt_bpa_target
      - name: stt_tlst_target
      - name: stt_bincol_target
      - name: stt_mix_target
      - name: cbrs_hours
      - name: cbrs_hours_act_stt
      - name: cbrs_hours_stt_upt
      - name: cbrs_hours_stt_acu
      - name: cbrs_hours_stt_uit
      - name: cbrs_hours_stt_cct
      - name: cbrs_hours_stt_apc
      - name: cbrs_hours_stt_bpa
      - name: cbrs_hours_stt_tlst
      - name: cbrs_hours_stt_bincol
      - name: cbrs_hours_stt_mix

